project:
  type: website

website:
  title: "Greatest Albums of All Time"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Top 50
      - href: about.qmd
        text: About

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

