project:
  type: website

website:
  title: "Greatest Albums of All Time"
  back-to-top-navigation: true
  repo-url: https://github.com/ahasoplakus/rollingstones/
  repo-branch: master
  repo-actions: [source]

  navbar:
    left:
      - href: index.qmd
        text: Top 50
      - href: about.qmd
        text: Author
        icon: person-bounding-box

format:
  html:
    theme: united
    smooth-scroll: true
    css: styles.css
    toc: true
    page-layout: full

editor: visual

