project:
  type: website

website:
  title: "Greatest Albums of All Time"
  navbar:
    left:
      - href: index.qmd
        text: Album Rankings
      - href: about.qmd
        text: About

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

